### PR TITLE
Added Rust Bindings for Termux GUI

### PR DESCRIPTION
**Pull request by sweetkitty13**

### CODE REVIEW

**Comment by tareksander** [comment]
Before you go on and implement the other features, I'm making a binary version of the protocol using protocol buffers for the next release, that might be easier to use in type-safe languages and should also increase performance. That's also the reason why I haven't made the C/C++ library yet. Depending on if you like the design of the C/C++ library, you could also make a Rust wrapper for that when it is finished. I'm also considering making the C/C++ library in Rust and just generating the C/C++ header files for that.

**Comment by sweetkitty13** [comment]
I think it is better if you write the lib in C for maximum portability(ie, to use in languages other than Rust)

**Comment by sweetkitty13** [comment]
Actually I completed all implementations(It took me 2 day or so except buffer since I am new to socket programming). I didn't push it because I had to prepare for an exam.(So, didn't get time to compile a documentation and do some tests). So, should I wait?

**Comment by tareksander** [comment]
If you already finished everything that's great too. If you want to avoid the nightly version of Rust, you can probably get the raw file descriptor for the socket and use the standard C functions for ancillary data with unsafe code. I made a function in C to receive exactly one fd as an ancillary message: https://github.com/tareksander/termux-app/blob/plugin-system/termux-shared/src/main/cpp/local-socket.cpp#L606-L679
  
  
Also see the man pages for cmsg and recvmsg.

**Comment by tareksander** [comment]
@sweetkitty13 I separated the language bindings section into official and community, is that okay with you?

**Comment by sweetkitty13** [comment]
> @sweetkitty13 I separated the language bindings section into official and community, is that okay with you?

Yep

**Comment by sweetkitty13** [comment]
So, now I am closing this in favour of https://github.com/termux/termux-gui/pull/28/commits/693b203007cce59a1bb65f967d743ccfa6842bbb

**Comment by sweetkitty13** [comment]
So, now I am closing this in favour of https://github.com/termux/termux-gui/pull/28/commits/693b203007cce59a1bb65f967d743ccfa6842bbb

**Comment by tareksander** [comment]
> So, now I am closing this in favour of [693b203](https://github.com/termux/termux-gui/commit/693b203007cce59a1bb65f967d743ccfa6842bbb)

I actually added that commit to this PR (a Github feature that people with write access to the original repo can commit to the PR if you enable it), merged it now.

By the way @sweetkitty13, you're the first person I know that implemented the protocol themselves, is it easy to understand? Is the protocol documentation enough? Do you feel features are missing?

**Comment by sweetkitty13** [comment]
> > So, now I am closing this in favour of [693b203](https://github.com/termux/termux-gui/commit/693b203007cce59a1bb65f967d743ccfa6842bbb)
> 
> I actually added that commit to this PR (a Github feature that people with write access to the original repo can commit to the PR if you enable it), merged it now.
> 
> By the way @sweetkitty13, you're the first person I know that implemented the protocol themselves, is it easy to understand? Is the protocol documentation enough? Do you feel features are missing?

It was easy thanks to your python bindings and Protocol.md. I had to learn Unix Sockets but thanks to your C++ bindings, I was able to figure out what was happening.

**Pull request merged**
